# Generated by Django 2.0.2 on 2018-04-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20180404_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='formOnline',
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
