# Generated by Django 2.0.2 on 2018-04-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20180404_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
