# Generated by Django 2.0.2 on 2018-04-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20180404_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='content',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
