# Generated by Django 2.0.2 on 2018-04-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_form_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='form',
            name='content',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
