# Generated by Django 2.0.3 on 2018-07-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
