# Generated by Django 2.0.3 on 2018-07-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180709_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='content',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
