# Generated by Django 2.0.3 on 2018-07-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20180709_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='content',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
