# Generated by Django 2.0.2 on 2018-03-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news_public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
                ('file', models.CharField(max_length=1000)),
            ],
        ),
    ]
