# Generated by Django 2.0.2 on 2018-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180330_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('content', models.TextField(max_length=1000)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
