# Generated by Django 2.0.2 on 2018-04-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
