# Generated by Django 2.0.2 on 2018-04-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180401_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
