# Generated by Django 2.0.2 on 2018-04-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180401_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='public',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
