# Generated by Django 2.0.3 on 2018-07-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180413_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='content',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='content',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
